---
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules: {}
