---
# This workflow will do a clean installation of node dependencies,
#   cache/restore them,
#   build the source code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches-ignore: [dist]
  pull_request:
    branches-ignore: [dist]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
        # See supported Node.js release schedule
        # at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build from TypeScript
        run: pnpm run build
      - name: ESLint
        run: pnpm run lint
      - name: Run script
        run: pnpm run start
      - name: Prettier
        run: pnpm exec prettier --check .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build artifact
        run: pnpm run start
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  push:
    needs: build
    if: >-
      ${{ github.repository_owner == 'extend-luogu'
      && github.event_name == 'push'
      && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: .
      - name: Push to branch `dist'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: |
            ${{ github.event.head_commit.timestamp }}

            Commit ${{ github.sha }}
