---
name: yamllint

on:
  push:
    branches-ignore: [dist]
  pull_request:
    branches-ignore: [dist]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: sudo apt-get install -yqq yamllint
      - run: yamllint .
